# Generated by Django 3.1.5 on 2021-01-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=200)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
