# Generated by Django 3.1.5 on 2021-01-31 03:02

import django.core.files.storage
from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210131_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bookupload',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/Users/emilyhuang/PycharmProjects/bookTrade/src/media/my_sell/'), upload_to=payments.models.image_directory_path),
        ),
    ]
