# Generated by Django 3.1.5 on 2021-01-31 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210131_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
