# Generated by Django 3.1.5 on 2021-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sell_topics', models.CharField(max_length=100)),
                ('buy_topics', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('study_topics', models.CharField(max_length=100)),
            ],
        ),
    ]
