# Generated by Django 3.1.5 on 2021-01-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_matching_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=100),
        ),
    ]
